# Change your language. Supported languages
# en_us - English
# ro_ro - Romanian
# fr_fr - French
# de_de - German
# es_es - Spanish
# More to come...
language: en_us

# Will there be automatic backups
autoBackups: true

# How often the server will automatically backup in seconds; default is every 12 hours
autoBackupFrequency: 43200

# Console backup print frequency by percent. ex: 5 would print every 5%
backupPrintFrequency: 5

# Path to backup folder. '' by default
backupFolderDirectory: ''

# To include the plugins' jar files
includePluginJars: false

# To include the plugins' jar files
includeServerJar: false

# What folders you dont want backed up
backupFolderExceptions:
  - 'backups'
  - 'cache'
  - 'logs'

# Which file extensions you dont want backed up
backupExtensionExceptions:
  - 'jar'
  - 'bat'

# format that backups will be named. &%date%& will be replaced with the date
backupNameFormat: 'Server-Backup-%date%'

# Format that the date will be presented. For syntax, consult https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
dateFormat: 'yyyy-MM-dd_HH-mm-ss'

# IF you want full player saves that are in that world to be rolled back or not(Location will always be rolled back)
restorePlayerWithWorld: true

# Amount of seconds between update checks
updateCheckInterval: 3600
