name: ${artifactId}
author: Zach Warunek
main: com.github.zwarunek.timemachine.TimeMachine
version: ${project.version}
api-version: 1.13
load: STARTUP
description: An easy and simple server backup solution
commands:
  timemachine:
    aliases: [tm, tmb]
    description: command for changing settings and functionality
    usage: /<command> help
permissions:
  timemachine:
    default: op
    description: Lets the player access this plugin
